title: NH-HIKE Adventures
description: Welcome to NH-HIKE <br> Your outdoor adventure starts here
url: https://nhhike.com
baseurl: ""

show_downloads: false
google_analytics: ""
# Force rebuild to sync scripts across all pages
plugins:
  - jekyll-remote-theme
